name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Build Docker images for the generator and reader services
      - name: Build Docker images
        run: docker-compose build

      # Push Docker images to DockerHub
      - name: Push Docker images to DockerHub
        run: docker-compose push

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Runs after the build job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy your application (e.g., to a cloud service)
      - name: Deploy to server
        run: |
          ssh user@your-server "docker-compose down && docker-compose pull && docker-compose up -d"
