name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the generator Docker image
      - name: Build Generator Image
        run: |
          cd generator
          docker build -t yourusername/generator:latest .

      # Push the generator Docker image to DockerHub
      - name: Push Generator Image to DockerHub
        run: |
          docker push yourusername/generator:latest

      # Build the reader Docker image
      - name: Build Reader Image
        run: |
          cd reader
          docker build -t yourusername/reader:latest .

      # Push the reader Docker image to DockerHub
      - name: Push Reader Image to DockerHub
        run: |
          docker push yourusername/reader:latest
